name: Build cache

on: 
  #push:
    #branches:
    #- "*"
  workflow_dispatch:
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [MI-R4A]
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: '**/go.sum'   
      - name: Prepare
        run: |
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
          # workaround for actions/setup-go#107
          sudo rm -f /bin/go && sudo ln -s -f /usr/bin/go $GOROOT/bin/go
          echo "DIR=/opt/Padavan-KVR" >> $GITHUB_ENV
      - name: Set golang
        run: |
         cp -f bashScripts/go.sh $(pwd)
         sudo chmod 777 ./go.sh
         bash ./go.sh
      - name: Clone source code
        run: |
           git clone --depth=1 https://github.com/vipshmily/Padavan-KVR.git ${{ env.DIR }}
           cd ${{ env.DIR }}/toolchain-mipsel
           sh dl_toolchain.sh
           mkdir -p /opt/images/
      - name: Start build
        env:
          MHZ: 1120               # CPU超频频率 必须为20的倍数
        run: |
         cp -f public/MI-R4A.config ${{ env.DIR }}/trunk/configs/templates
         #cp -f public/ssr-monitor ${{ env.DIR }}/trunk/user/shadowsocks/scripts
         #cp -f public/shadowsocks.sh ${{ env.DIR }}/trunk/user/shadowsocks/scripts
         cp -f public/adguardhome.sh ${{ env.DIR }}/trunk/user/adguardhome
         #cp -f public/build_firmware_modify ${{ env.DIR }}/trunk
         cd ${{ env.DIR }}/trunk
         echo "CPU超频到$MHZ"mhz
         echo "修改CPU频率"
         clock=`echo "obase=16 ; ibase=10 ; (((($MHZ/20)-1)*16+2))" | bc`
         echo "16进制$clock"
         sed -i "554,555s:0xff:0x7ff:g" ${{ env.DIR }}/trunk/linux-3.4.x/arch/mips/rt2880/init.c
         sed -i "554,556s:0xc2:0x$clock:g" ${{ env.DIR }}/trunk/linux-3.4.x/arch/mips/rt2880/init.c
          fakeroot ./build_firmware_ci ${{ matrix.targets }}
          echo "TAG_ANME=$(TZ='Asia/Shanghai' date +%Y.%m.%d-%H%M)" >> $GITHUB_ENV
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: ${{ env.DIR }}/trunk/images/*.trx
      - name: Update Release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: ${{ env.DIR }}/trunk/images/*.trx
          allowUpdates: true
